spring:
  application:
    name: API-GATEWAY
server:
  port: 3333
zuul:
  prefix: /ms
  routes:
    greet:
      path: /api1/**
      serviceId: GREET-API
    welcome:
      path: /api2/**
      serviceId: WELCOME-API